spring.application.name=alld

# ===============================
# = DATA SOURCE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://db:3306/dba
spring.datasource.username=rwroot
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
# Hibernate dialect for MySQL 8.x
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Schema handling
# validate = check schema matches, no changes
# update   = auto update schema
# create   = create schema at startup (drops existing)
# create-drop = drop schema at shutdown
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# = CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# ===============================
# = LOGGING (Optional for debugging)
# ===============================
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# Comma-separated list of allowed origins
app.cors.allowed-origins=http://localhost:4080,https://your-production-domain.com,http://103.29.62.25:4080,https://103.29.62.25:5082

# Where files actually live (OLD + NEW)
app.upload.base-path=/opt/dbaalld01_project/deploy-dba_alld_project/backend/
media.base-url=https://103.29.62.25:4082
app.log.dir=${APP_LOG_DIR:/var/log/dba-alld}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# s3Bucket Setup (non-prod)
aws.s3.bucket.name=amazn-s3-dbaalld-dev

#Google re-CAPTCHA
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY:6LfXhYEsAAAAACaV-ufthOMNP-lf1j1nDJXAwyi9}
recaptcha.verify-url=${RECAPTCHA_VERIFY_URL:https://www.google.com/recaptcha/api/siteverify}
recaptcha.fail-fast-on-missing-secret=${RECAPTCHA_FAIL_FAST:true}

