global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dba-backend-prod'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dba-prod-backend:8090']
    relabel_configs:
      - source_labels: []
        target_label: environment
        replacement: 'prod'
      - source_labels: []
        target_label: instance
        replacement: 'prod-backend'
