apiVersion: 1

datasources:
  - name: Prometheus-PROD
    type: prometheus
    access: proxy
    url: http://dba-prod-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
