apiVersion: 1

datasources:
  - name: Prometheus-DEV
    type: prometheus
    access: proxy
    url: http://dba-dev-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
