name: Deploy to prod

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: [self-hosted, dba-alld-server]
    environment: production
    steps:
      - name: Deploy
        run: bash /home/dbadev01/dba-prodv3/src/alld-backend/deployment/scripts/ci-deploy.sh prod /home/dbadev01/dba-prodv3 6704
