name: Deploy to dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: [self-hosted, dba-alld-server]
    environment: dev
    steps:
      - name: Deploy
        run: bash /home/dbadev01/dba-devv2/src/alld-backend/deployment/scripts/ci-deploy.sh dev /home/dbadev01/dba-devv2 5602
